# These settings are synced to GitHub by https://probot.github.io/apps/settings/

branches:
  - name: main
    protection:
      enforce_admins: false
      required_pull_request_reviews:
        dismiss_stale_reviews: true
        require_code_owner_reviews: false
        required_approving_review_count: 1
      required_status_checks:
        strict: true
        contexts:
          #          - "Code Style (ubuntu-latest, 8.1)"
          - "Static Analysis (ubuntu-latest, 8.1)"
          - "Unit Tests (ubuntu-latest, 8.1)"
      restrictions: null
      required_linear_history: true

repository:
  allow_merge_commit: true
  allow_rebase_merge: true
  allow_squash_merge: true
  delete_branch_on_merge: true
  default_branch: main
  description: "Monorepo for all PHP Addition Repository (PAR) packages"
  homepage: https://php-addition-repository.github.io/
  #  topics: collection
  has_downloads: false
  has_issues: true
  has_pages: false
  has_projects: false
  has_wiki: false
  name: par
  private: false
