version: '3.7'

networks:
  backend:
    driver: ${NETWORKS_DRIVER-bridge}

services:
  workspace:
    build:
      context: .
      dockerfile: .docker/workspace/Dockerfile
    volumes:
      - ~/.ssh:/home/app/.ssh
      - ~/.gitconfig:/home/app/.gitconfig
      - .:/app
    tty: true
    networks:
      - backend