name: Code Analysis

on:
  pull_request: null
  push:
    branches:
      - main

jobs:
  code_analysis:
    strategy:
      fail-fast: false
      matrix:
        actions:
          - name: Composer Validate
            run: composer validate --strict

          - name: Monorepo-builder Validate
            run: vendor/bin/monorepo-builder validate

          - name: Psalm
            run: vendor/bin/psalm

    name: ${{ matrix.actions.name }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0
          extensions: intl, ds
          coverage: none
          tools: composer

      - name: Cache PHP dependencies
        uses: actions/cache@v1
        with:
          path: vendor
          key: ${{ runner.OS }}-build-${{ hashFiles('**/composer.lock') }}
      - run: composer install --no-progress --ansi

      - run: ${{ matrix.actions.run }}