name: Docs

on:
  push:
    branches:
      - main

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0
          coverage: none
          tools: composer:v2

      - name: Cache PHP dependencies
        uses: actions/cache@v1
        with:
          path: vendor
          key: ${{ runner.OS }}-build-${{ hashFiles('**/composer.lock') }}
      - run: composer install --no-progress --ansi

      - name: Generate docs
        uses: phpDocumentor/phpDocumentor@master

      - name: Pushes to another repository
        uses: cpina/github-action-push-to-another-repository@master
        env:
          API_TOKEN_GITHUB: ${{ secrets.REPO_GIT_TOKEN }}
        with:
          source-directory: 'docs'
          destination-github-username: 'php-addition-repository'
          destination-repository-name: 'php-addition-repository.github.io'
          user-email: brouwer.alexander@gmail.com