name: 'Packages Split'

on:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  provide_packages_json:
    # see json juggling: https://docs.github.com/en/free-pro-team@latest/actions/reference/context-and-expression-syntax-for-github-actions#example-6
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          extensions: intl
          tools: none

      - name: Install dependencies
        uses: ramsey/composer-install@v2

      # get package json list
      - id: packages
        run: echo "packages=$(vendor/bin/monorepo-builder packages-json --exclude-package docs)" >> $GITHUB_OUTPUT
  
    # this step is needed, so the output gets to the next defined job
    outputs:
      packages: ${{ steps.packages.outputs.packages }}

  split_monorepo:
    needs: provide_packages_json

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package: ${{ fromJson(needs.provide_packages_json.outputs.packages) }}

    steps:
      - uses: actions/checkout@v2

      # no tag
      - if: "!startsWith(github.ref, 'refs/tags/')"
        name: Split into ${{ matrix.package }}
        uses: "symplify/monorepo-split-github-action@2.2"
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          package-directory: "packages/${{ matrix.package }}"
          split-repository-organization: "php-addition-repository"
          split-repository-name: "${{ matrix.package }}"
          user-name: "GitHub Action"
          user-email: "action@github.com"
          branch: "main"

      # with tag
      - if: "startsWith(github.ref, 'refs/tags/')"
        name: Split into ${{ matrix.package }}
        uses: "symplify/monorepo-split-github-action@2.2"
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          tag: ${GITHUB_REF#refs/tags/}
          package-directory: "packages/${{ matrix.package }}"
          split-repository-organization: "php-addition-repository"
          split-repository-name: "${{ matrix.package }}"
          user-name: "GitHub Action"
          user-email: "action@github.com"
          branch: "main"
