name: Split Monorepo

on:
  push:
    branches:
      - master

jobs:
  provide_packages_json:
    # see json juggling: https://docs.github.com/en/free-pro-team@latest/actions/reference/context-and-expression-syntax-for-github-actions#example-6
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      # required for matrix of packages set
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          coverage: none
          tools: composer:v2
      
      - run: composer install --no-progress --ansi
      
      # get package json list
      - id: set-matrix
        run: echo "::set-output name=matrix::$(vendor/bin/monorepo-builder packages-json)"
  
  split_monorepo:
    needs: provide_packages_json
    
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: ${{fromJson(needs.provide_packages_json.outputs.matrix)}}
    
    steps:
      - uses: actions/checkout@v2
        # this is required for "WyriHaximus/github-action-get-previous-tag" workflow
        # see https://github.com/actions/checkout#fetch-all-history-for-all-tags-and-branches
        with:
          fetch-depth: 0
      
      # see https://github.com/WyriHaximus/github-action-get-previous-tag
      - id: previous_tag
        uses: "WyriHaximus/github-action-get-previous-tag@master"
      
      - # Uses an action in the root directory
        uses: TomasVotruba/github-action-monorepo-split@master
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        with:
          package-directory: 'packages/${{ matrix.package_name }}'
          split-repository-organization: 'par'
          split-repository-name: '${{ matrix.package_name }}'
          tag: ${{ steps.previous_tag.outputs.tag }}
      