name: Split Monorepo

on:
  push:
    branches:
      - main
  
    # see https://github.community/t/how-to-run-github-actions-workflow-only-for-new-tags/16075/10?u=tomasvotruba
    tags:
      - '*'

jobs:
  provide_packages_json:
    # see json juggling: https://docs.github.com/en/free-pro-team@latest/actions/reference/context-and-expression-syntax-for-github-actions#example-6
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      # required for matrix of packages set
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0
          coverage: none
          tools: composer:v2

      - name: Cache PHP dependencies
        uses: actions/cache@v1
        with:
          path: vendor
          key: ${{ runner.OS }}-build-${{ hashFiles('**/composer.lock') }}
      - run: composer install --no-progress --ansi

      # get package json list
      - id: output_data
        run: echo "::set-output name=matrix::$(vendor/bin/monorepo-builder packages-json)"
  
    # this step is needed, so the output gets to the next defined job
    outputs:
      matrix: ${{ steps.output_data.outputs.matrix }}

  split_monorepo:
    needs: provide_packages_json

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package: ${{fromJson(needs.provide_packages_json.outputs.matrix)}}

    steps:
      - uses: actions/checkout@v2

      - name: Generate docs
        uses: docker://phpdoc/phpdoc:3
        with:
          workdir: '/github/workspace'
          args: 'project:run'

      - # Uses an action in the root directory
        name: Monorepo Split of ${{ matrix.package }}
        uses: symplify/github-action-monorepo-split@master
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_GIT_TOKEN }}
        with:
          package-directory: 'packages/${{ matrix.package }}'
          split-repository-organization: 'php-addition-repository'
          split-repository-name: '${{ matrix.package }}'
          branch: 'main'
          user-name: 'Alex Brouwer'
          user-email: 'brouwer.alexander@gmail.com'
      