name: Unit tests

on:
  pull_request: null
  push:
    branches:
      - main

jobs:
  unit_tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [ '8.1', '8.2' ]

    name: PHP ${{ matrix.php }} tests
    steps:
      - uses: actions/checkout@v2

      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: intl, ds
          coverage: none
          tools: composer

      - name: Cache PHP dependencies
        uses: actions/cache@v1
        with:
          path: vendor
          key: ${{ runner.OS }}-build-${{ hashFiles('**/composer.lock') }}
      - run: composer install --no-progress --ansi

      - run: vendor/bin/phpunit
